<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <AssemblyName>Observable.Tests</AssemblyName>
    <RootNamespace>Skclusive.Mobx.Observable.Tests</RootNamespace>
    <Authors>Skclusive</Authors>
    <Company>Skclusive</Company>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ImpromptuInterface" Version="8.0.6" />
    <PackageReference Include="xunit.v3" Version="4.0.1" />
    <PackageReference Include="xunit.v3.assert" Version="4.0.1" />
    <PackageReference Include="xunit.v3.mtp-v2" Version="4.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\src\Observable.csproj" />
  </ItemGroup>

</Project>